name: playChristmas
author: lightPlugins
version: '${project.version}'
main: io.lightplugins.christmas.LightMaster
api-version: 1.21
depend: ["PlaceholderAPI", "ProtocolLib"]
softdepend: []
loadbefore: []
libraries: []
#  - org.mariadb.jdbc:mariadb-java-client:2.7.4
#  - com.zaxxer:HikariCP:5.1.0
commands:
  advent:
    description: The root command for the module adventcalendar
    aliases: [ac, adventskalender]
  secretsanta:
    description: The root command for the module secretsanta
    aliases: [sa, wichteln]
  sledhunt:
    description: The root command for the module sledhunt
    aliases: [sh, schlittenjagd]